"""empty message

Revision ID: 570db6da3137
Revises: df213055e049
Create Date: 2025-12-25 18:46:14.681270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570db6da3137'
down_revision = 'df213055e049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
